language: node_js
node_js:
- '6'
os:
- linux
sudo: true
cache:
  directories:
  - node_modules
before_install:
- sudo add-apt-repository --yes ppa:arx/release
- sudo apt-get update -d
- sudo apt-get install -y -q innoextract wine python-software-properties
- wine --version
- innoextract --version
- "./scripts/innosetup/innoinstall.sh"
- sudo cp scripts/innosetup/iscc /usr/local/bin/iscc
- iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"
before_script:
- npm install
- npm install gulp -g
script: npm test
after_success:
- gulp build
- "./scripts/download_git.sh ./vendor 2.9.2 64"
- "./scripts/download_git.sh ./vendor 2.9.2 32"
- iscc win64_installer.iss
- iscc win32_installer.iss
before_deploy:
- echo "deploying builds"
deploy:
  provider: releases
  api_key:
    secure: brjmL3cyCTr6swNCqka2fkc41j+PO2tqXZhE9QyNoDEXcxR1FOwPoPut/8h4N/pISfkf2FibtsWqThhW1Xz1pVNNMBlHRblJsSecfvXOtn7kneCsAV+QBngbPuA8OKzfhXTUeIQNlIpfG+rwlDg28wOthDI/7ADBOYgGQWeOd7o=
  file:
    - out/build/tS_9.2-28_win_x32.exe
    - out/build/tS_9.2-28_win_x64.exe
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: unfoldingWord-dev/ts-desktop
