language: node_js
node_js:
- '5'
- '6'
sudo: false
before_script:
- npm install
#- npm install gulp -g
script: npm test
#before_install:
#- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_54b2df9dba46_key -iv $encrypted_54b2df9dba46_iv -in config.json.enc -out unit_tests/git/config.json -d; fi

