language: node_js
node_js:
- '5'
- '6'
os:
- 'linux'
- 'os'
sudo: true
before_install:
- apt-get install wine && wine wineboot
- add-apt-repository --yes ppa:arx/release
- apt-get update -d
- apt-get install -y -q innoextract
- wget -O is.exe http://www.jrsoftware.org/download.php/is.exe
- innoextract is.exe
- mkdir -p ~/".wine/drive_c/inno"
- cp -a app/* ~/".wine/drive_c/inno"

before_script:
- npm install
- npm install gulp -g
script: npm test
after_success:
- gulp build

#before_install:
#- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_54b2df9dba46_key -iv $encrypted_54b2df9dba46_iv -in config.json.enc -out unit_tests/git/config.json -d; fi

